# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  name: 'Default' 
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.0.28'
  projectPath: '/c/xampp/htdocs/TinyBlogger'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    displayName: 'Build job'
    steps:
    - script: |
        # Display PHP version to verify installation
        php -version

        # Navigate to the root folder of your PHP project
        cd $(projectPath)

        # Install dependencies using Composer
        $(PHP_EXE) -v
        $(COMPOSER_EXE) install --no-interaction --prefer-dist

        # Run any additional commands needed for your build process
      displayName: 'Use PHP version 7.3 and Install Dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectPath)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Upload package'
      artifact: 'drop'

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    displayName: 'Deploy job'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : TinyBlogger'
            inputs:
              azureSubscription: 'Tiny-Blogger subscription'
              appName: 'YourWebAppName'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              appType: 'webapp'